import bot from "./assets/bot.svg";
import user from "./assets/user.svg";

const form = document.querySelector("form");
const chatContainer = document.getElementById("chat__container");

let loadInterval;

// AI loads three dots whilst request is being generated by the user.
function loader(element) {
  element.textContent = "";

  loadInterval = setInterval(() => {
    element.textContent += ".";

    if (element.textContent === "....") {
      element.textContent = "";
    }
  }, 300);
}

// AI types output/answer letter by letter to create an response effect.
function typeText(element, text) {
  let index = 0;

  let interval = setInterval(() => {
    if (index < text.length) {
      element.innerHTML += text.charAt(index);
      index++;
    } else {
      clearInterval(interval);
    }
  }, 20);
}

// Generate a unique ID for every message to map over them

function generateUniqueID() {
  const timestamp = Date.now();
  const randomNumber = Math.random();
  const hexadecimalString = randomNumber.toString(16);

  return `id-$(timestamp)-$(hexadecimalString)`;
}

//

function chatStripe(isAi, value, uniqueId) {
  return (
    `
      <div class="wrapper ${isAi && "ai"}">
        <div class="chat">
          <div className="profile">
            <img 
            src="${isAi ? bot : user}"
            alt="${isAi ? "bot" : "user"}"
            />
          </div>
          <div class="message" id=${uniqueId}>${value}</div>
        </div>
      </div>
    `
  )
}

const handleSubmit = asymc(e);
